### ISSUE TITLE
Can not read image by your plugin

### ISSUE THREAD

**Issue by Bazarganigilani** [gobeam/vue-polygon-cropper#6]
I am using a third party component in vue named polygoncropper (https://github.com/gobeam/vue-polygon-cropper/tree/master/example/), I have downloaded the codes and using my local machine, and then I used below comands to build and run the sample,

npm install
npm run serve

and then the sample page comes up correctly but the problem is that, I can not work with its loading image, whenever I want to load a new image, it doesn't show up into the canvas and I have to do reset, for example at below I am loading an image with the name of "emco.jpg", but the original image demo.png has been remained! I am not sure how to fix this error?
![image](https://user-images.githubusercontent.com/25941088/103743566-7c6c2500-5050-11eb-9405-7a7d2a151219.png)

**Comment by gobeam** [comment]
It is fixed in latest master branch @Bazarganigilani please pull latest master branch and run the code. It should work fine. Don't forget to close the issue and star the repo if you like it.

**Comment by Bazarganigilani** [comment]
Hi, using your latest codes from master branch,

I am getting following error when I run npm run serve:

 ```
ERROR  Failed to compile with 1 errors                                                                                                                          10:11:41 pm

This relative module was not found:

* ../../dist/PolygonCropper.umd in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
```

**Comment by gobeam** [comment]
> Hi, using your latest codes from master branch,
> 
> I am getting following error when I run below commands in example directory:
> 
> ```
> npm install
> npm run serve
> ```
> 
> ```
> ERROR  Failed to compile with 1 errors                                                                                                                          10:11:41 pm
> 
> This relative module was not found:
> 
> * ../../dist/PolygonCropper.umd in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
> ```

You have to build source code for vue-cropper plugin first I've removed dependency from npm, run 
`npm run build`
 on root folder first. then only run 
`npm run serve`
 from example directory

**Comment by Bazarganigilani** [comment]
Hi,
even by running "npm run build", I am getting the same error:

```
 ERROR  Failed to compile with 1 errors                                                                                                                          10:39:19 pm

This relative module was not found:

* ../../dist/PolygonCropper.umd in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
```
