### ISSUE TITLE
Converting to your plugin to react.js component

### ISSUE THREAD

**Issue by Bazarganigilani** [gobeam/vue-polygon-cropper#7]
Hi,

I am just trying to use your plugin as a component in my reactjs application. I have abit changed your plugin slightly and pushed the codes to [here](https://github.com/Bazarganigilani/vue_sample)

I then build the plugin by using 
`vue-cli-service build --target wc --name my-app src/App.vue`

using the js file inside dis folder

I am trying to run my react app but I get below error when I use the js file inside my react app
`import "components/PolygonCropper/my-app.js";`

I am getting below error when I compile my react.js application

```
Failed to compile.

./src/components/PolygonCropper/my-app.js
  Line 139:4:      Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 3990:475:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 3990:1058:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 3990:1238:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 3990:1435:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 37299:5:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 37304:10:   Unexpected use of 'self'                                               no-restricted-globals
  Line 37304:33:   Unexpected use of 'self'                                               no-restricted-globals
  Line 37388:18:   'Vue' is not defined                                                   no-undef
  Line 37949:16:   Unexpected use of 'self'                                               no-restricted-globals
  Line 37949:36:   Unexpected use of 'self'                                               no-restricted-globals

```
Can you help me convert your plugin to a react component successfully?

**Comment by gobeam** [comment]
Sorry this plugin is only for Vue application.

**Comment by Bazarganigilani** [comment]
Hi, I can successfully build your plugin as a web component (a js file) now I am trying to put this js file inside my react, I tried helmet and react-script-loader but without any success.

I am looking for  a way to integrate this into my react application!
